annotsv_colnames <- c(
  "AnnotSV ID",
    "SV chrom",
    "SV start",
    "SV end",
    "SV length",
    "SV type",
    "Samples_ID",
    "ID",
    "REF",
    "ALT",
    "QUAL",
    "FILTER",
    "INFO",
    "FORMAT",
    "Einstein",
    "AnnotSV type",
    "Gene name",
    "tx",
    "CDS length",
    "frameshift",
    "tx length",
    "location",
    "location2",
    "distNearestSS",
    "nearestSStype",
    "intersectStart",
    "intersectEnd",
    "DGV_GAIN_IDs",
    "DGV_GAIN_n_samples_with_SV",
    "DGV_GAIN_n_samples_tested",
    "DGV_GAIN_Frequency",
    "DGV_LOSS_IDs",
    "DGV_LOSS_n_samples_with_SV",
    "DGV_LOSS_n_samples_tested",
    "DGV_LOSS_Frequency",
    "GD_ID",
    "GD_AN",
    "GD_N_HET",
    "GD_N_HOMALT",
    "GD_AF",
    "GD_POPMAX_AF",
    "GD_ID_others",
    "1000g_event",
    "IMH_ID",
    "IMH_AF",
    "IMH_ID_others",
    "promoters",
    "dbVar_event",
    "dbVar_variant",
    "dbVar_status",
    "TADcoordinates",
    "ENCODEexperiments",
    "GCcontent_left",
    "GCcontent_right",
    "Repeats_coord_left",
    "Repeats_type_left",
    "Repeats_coord_right",
    "Repeats_type_right",
    "Gap_left",
    "Gap_right",
    "SegDup_left",
    "SegDup_right",
    "ENCODE_blacklist_left",
    "ENCODE_blacklist_characteristics_left",
    "ENCODE_blacklist_right",
    "ENCODE_blacklist_characteristics_right",
    "ACMG",
    "HI_CGscore",
    "TriS_CGscore",
    "DDD_status",
    "DDD_mode",
    "DDD_consequence",
    "DDD_disease",
    "DDD_pmids",
    "HI_DDDpercent",
    "delZ_ExAC",
    "dupZ_ExAC",
    "cnvZ_ExAC",
    "synZ_ExAC",
    "misZ_ExAC",
    "pLI_ExAC",
    "Mim Number",
    "Phenotypes",
    "Inheritance",
    "morbidGenes",
    "morbidGenesCandidates",
    "AnnotSV ranking",
    "ranking decision criteria"
)